services:
  db:
    image: postgres:15-alpine
    environment: 
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432